name: 🚢 Deploy to Azure

on:
  workflow_dispatch:
    inputs:
      api_image:
        description: 'API Container Image'
        required: true
        type: string
      api_digest:
        description: 'API Container Digest (sha256:...)'
        required: true
        type: string
      api_name:
        description: 'API Package Name'
        required: true
        type: string
      frontend_image:
        description: 'Frontend Container Image'
        required: true
        type: string
      frontend_digest:
        description: 'Frontend Container Digest (sha256:...)'
        required: true
        type: string
      frontend_name:
        description: 'Frontend Package Name'
        required: true
        type: string


env:
  AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
  AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
  AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
  RESOURCE_GROUP_NAME: ${{ vars.AZURE_RESOURCE_GROUP_NAME }}
  DEMO_INSTANCE_NAME: octocat_supply-obscure-bassoon
  DEMO_SLUG: octocat_supply
  GITHUB_HOSTNAME: "github.com"
  REGISTRY_HOSTNAME: "ghcr.io"
  REGISTRY_URL: "https://ghcr.io/${{ github.repository_owner }}"
  ARTIFACT_URL: "https://github.com/${{ github.repository }}/pkgs/container"
  CONTAINER_APP_ENVIRONMENT_NAME: octocat-supply-cae
  CONTAINER_APP_ENVIRONMENT_ID: /subscriptions/408de6dc-726d-4e63-87d3-ef5bbbb30d9e/resourceGroups/dotcom--msft-common-demos--octocat-supply-resources/providers/Microsoft.App/managedEnvironments/octocat-supply-cae


jobs:
  deploy:
    name: Azure deployment disabled
    runs-on: ubuntu-latest

    steps:
      - name: Deployment disabled
        run: echo "Azure deployment was disabled in demo creation"
        shell: bash

